
##########################################################################################################################

version: "3"

networks:
  avb-dyn-dash-network:

services:

##########################################################################################################################

  nginx:
    image: melon-yellow/nginx-alpine-avb-dyn-dash-nginx
    container_name: avb-dyn-dash-nginx
    restart: always
    build: ./nginx
    env_file: .env
    ports:
      - "${APP_PORT}:${NGINX_SERVICE_PORT}"
    volumes:
      - ./php/:/var/www
      - ./nginx/config:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      - avb-dyn-dash-network

##########################################################################################################################

  php:
    image: melon-yellow/php-8-avb-dyn-dash
    container_name: avb-dyn-dash
    restart: always
    build:
      args:
        user: ${PHP_USER}
        uid: ${PHP_UID}
      context: ./php
    env_file: .env
    volumes:
      - ./php/:/var/www/
    networks:
      - avb-dyn-dash-network

##########################################################################################################################

  redis:
    image: melon-yellow/redis-6-avb-dyn-dash-redis
    container_name: avb-dyn-dash-redis
    restart: always
    build: ./redis
    env_file: .env
    command: redis-server
    networks:
      - avb-dyn-dash-network

##########################################################################################################################
