
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  dyn:
    image: melon-yellow/php-8-apache-avb-dash
    container_name: avb-dash
    build: ./dyn
    env_file: .env
    volumes:
      - ./dyn/:/var/www/html/dyn/
    ports:
      - "${PHP_APACHE_PORT}:80"
    depends_on:
      - db
    restart: always

##########################################################################################################################
